## numpy基本用法

In [ ]:
import numpy as np

In [2]:
li = [
    [1, 2, -4],
    [-2, 2, 1],
    [-3, 4, -2],
]


In [4]:
matrix = np.array(li, dtype=np.str)

In [5]:
matrix

array([['1', '2', '-4'],
       ['-2', '2', '1'],
       ['-3', '4', '-2']], dtype='<U2')

In [6]:
print("matrix:", matrix)
print("matrix type:", type(matrix))   # <class 'numpy.ndarray'>  numpy的n维数组

print("matrix 维度:", matrix.ndim)
print("matrix 行列:", matrix.shape)
print("matrix 元素个数:", matrix.size)

matrix: [['1' '2' '-4']
 ['-2' '2' '1']
 ['-3' '4' '-2']]
matrix type: <class 'numpy.ndarray'>
matrix 维度:: 2
matrix 行列:: (3, 3)
matrix 元素个数:: 9


In [7]:
# 创建0矩阵
zero = np.zeros([3, 4], dtype=np.int)
print("0矩阵：zero:", zero)

0矩阵：zero: [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [8]:
# 创建全1矩阵
one = np.ones([2, 4], dtype=int)
print(one)


[[1 1 1 1]
 [1 1 1 1]]


In [9]:
# 创建全空数组，每个数都接近0
empty = np.empty([3, 3], )
print(empty)

[[0.00e+000 0.00e+000 0.00e+000]
 [0.00e+000 0.00e+000 6.82e-321]
 [0.00e+000 0.00e+000 0.00e+000]]


In [11]:
a  = np.arange(1,14,2)
print("连续数组", a)

连续数组 [ 1  3  5  7  9 11 13]


In [22]:
b = np.arange(12).reshape((3,4))
print("改变形状:", b)

改变形状: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [23]:
line_array = np.linspace(1, 10, 20)
print(line_array)


[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [27]:
# 线段形数组进行reshap
print(np.linspace(1, 10, 20).reshape(-1, 4))

[[ 1.          1.47368421  1.94736842  2.42105263]
 [ 2.89473684  3.36842105  3.84210526  4.31578947]
 [ 4.78947368  5.26315789  5.73684211  6.21052632]
 [ 6.68421053  7.15789474  7.63157895  8.10526316]
 [ 8.57894737  9.05263158  9.52631579 10.        ]]


In [26]:
st = "abcdef"
res = np.fromstring(st, dtype=np.int8)
print(res)
res2 = res.reshape(-1, 1)
print(res2)

[ 97  98  99 100 101 102]
[[ 97]
 [ 98]
 [ 99]
 [100]
 [101]
 [102]]


D:\Dev\Anaconda\envs\nlp\Lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  


In [30]:
c = np.linspace(1, 10, 20).reshape(-1, 4)
print(c)
print(c[1:, [3,2,1,0]])

[[ 1.          1.47368421  1.94736842  2.42105263]
 [ 2.89473684  3.36842105  3.84210526  4.31578947]
 [ 4.78947368  5.26315789  5.73684211  6.21052632]
 [ 6.68421053  7.15789474  7.63157895  8.10526316]
 [ 8.57894737  9.05263158  9.52631579 10.        ]]
[[ 4.31578947  3.84210526  3.36842105  2.89473684]
 [ 6.21052632  5.73684211  5.26315789  4.78947368]
 [ 8.10526316  7.63157895  7.15789474  6.68421053]
 [10.          9.52631579  9.05263158  8.57894737]]


关于numpy进行计算的一些操作练习

In [32]:
li = [1, 2, 3, 4]
a = np.array(li)
print(a, type(a))
print(a+1)

[1 2 3 4] <class 'numpy.ndarray'>
[2 3 4 5]


In [33]:
# 数组对应元素相加
b = np.array([2, 3, 4, 5])
print(a + b)       # [3 5 7 9]

[3 5 7 9]


In [34]:
# 对应元素相乘
print(a * b)       # [ 2  6 12 20]

[ 2  6 12 20]


In [35]:
# 对应元素乘方
print(a ** b)

[   1    8   81 1024]


In [36]:
print(a / b)

[0.5        0.66666667 0.75       0.8       ]


In [37]:
a = np.arange(20).reshape(4, 5)
b = np.arange(1,6)
print(a)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[1 2 3 4 5]


In [41]:
print(a*b)
print(a/b)
print(a+b)
print(a-b)

[[ 0  2  6 12 20]
 [ 5 12 21 32 45]
 [10 22 36 52 70]
 [15 32 51 72 95]]
[[ 0.          0.5         0.66666667  0.75        0.8       ]
 [ 5.          3.          2.33333333  2.          1.8       ]
 [10.          5.5         4.          3.25        2.8       ]
 [15.          8.          5.66666667  4.5         3.8       ]]
[[ 1  3  5  7  9]
 [ 6  8 10 12 14]
 [11 13 15 17 19]
 [16 18 20 22 24]]
[[-1 -1 -1 -1 -1]
 [ 4  4  4  4  4]
 [ 9  9  9  9  9]
 [14 14 14 14 14]]


## pandas基本用法

In [42]:
import pandas as pd

DataFrame就是一个SQL的表格Table
张量：二维矩阵即为二维张量
一张RGB图是张量
一个DataFrame 可以被表示成一个json, 也可以被表示成csv,可以被json所初始化

In [43]:
data = {
    'name': ['Alice', 'Bob', 'Charles', 'David', 'Eric'],
    'year': [2017, 2017, 2017, 2017,2017],
    'salary': [40000, 24000, 31000, 20000, 30000],
    'pair':[{'a':1},{'a':2},{'a':3},{'a':4},{'a':5}]
}

In [44]:
d = pd.DataFrame(data)
print(d)

      name  year  salary      pair
0    Alice  2017   40000  {'a': 1}
1      Bob  2017   24000  {'a': 2}
2  Charles  2017   31000  {'a': 3}
3    David  2017   20000  {'a': 4}
4     Eric  2017   30000  {'a': 5}


In [47]:
d['name']

0      Alice
1        Bob
2    Charles
3      David
4       Eric
Name: name, dtype: object

In [46]:
d.salary

0    40000
1    24000
2    31000
3    20000
4    30000
Name: salary, dtype: int64

In [49]:
print(type(d.salary))
d.salary.tolist()

<class 'pandas.core.series.Series'>


[40000, 24000, 31000, 20000, 30000]

In [50]:
d.salary[2]

31000

In [51]:
d.query('salary>30000')


name  year  salary      pair
0    Alice  2017   40000  {'a': 1}
2  Charles  2017   31000  {'a': 3}